import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <header></header>
        <aside
          className="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
          aria-label="Sidebar"
        >
          <div className="h-full overflow-y-auto bg-black flex justify-center items-center">
            <ul className="space-y-4">
              <li>
                <a
                  href=""
                  className="flex items-center text-white hover:text-green-500"
                >
                  <span className="text-base">Home</span>
                </a>
              </li>
              <li>
                <a
                  href="#resume"
                  className="flex items-center text-white hover:text-green-500"
                >
                  <span className="text-base">Resume</span>
                </a>
              </li>
            </ul>
          </div>
        </aside>
        <div className="sm:ml-64 bg-gray-950">{children}</div>
        <footer></footer>
      </body>
    </html>
  );
}
